ingress:
  enabled: true
  hosts:
  - acme.com
env:
  ELASTICSEARCH_HOSTS: http://elasticsearch-client:9200
resources:
  limits:
    cpu: 50m
    memory: 300Mi
  requests:
    cpu: 5m
    memory: 150Mi
